version: 2
jobs:
  cache-dependencies:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - &restore-cache
        restore_cache:
          key: app-cache-v1-{{ checksum "project.clj" }}
      - &install-lein-deps
        run:
          name: Install leiningen dependencies
          command: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: app-cache-v1-{{ checksum "project.clj" }}
  lint:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - *restore-cache
      - *install-lein-deps
      - run:
          command: lein cljfmt check
      - run:
          command: lein eastwood
  docker-test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - *restore-cache
      - run:
          name: Build the docker image
          command: |
            cp -r /home/circleci/.m2 .
            docker build .
      - run:
          name: Run the tests within a docker container
          command: |
            docker-compose build integration-tests
            docker-compose up -d
            docker-compose ps
            sleep 15
            lein flyway migrate
            docker-compose run integration-tests lein test

workflows:
  version: 2
  build-and-test:
    jobs:
      - cache-dependencies
      - lint:
          requires:
            - cache-dependencies
      - docker-test:
          requires:
            - cache-dependencies
