CREATE TABLE users(
   id VARCHAR(36) PRIMARY KEY NOT NULL,
   name VARCHAR(255) NOT NULL,
   created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
   updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE TABLE GAMES(
   id VARCHAR(36) PRIMARY KEY NOT NULL,
   value JSONB NOT NULL
);

CREATE TABLE GAME_PLAYERS(
 id VARCHAR(36) PRIMARY KEY NOT NULL,
 game_id VARCHAR(36) NOT NULL,
 player_id VARCHAR(36) NOT NULL,
 UNIQUE (game_id, player_id)
)
